In [1]:
import numpy as np

In [2]:
dt = 0.5
u_k = -2
S = 20
yk = np.pi/6
D = 40

Fk = np.array([[1.0,dt],[0.0,1.0]])
Lk = np.eye(2)
Gk = np.array([0.0,dt]).reshape((2,1))
Mk = 1

In [3]:
xh_k = np.array([0.0,5.0]).reshape(2,1)
Ph_k = np.array([[0.01,0],[0,1.0]])
v_k= np.array([0,0.01]).reshape(2,1)
R_k = 0.01
w_k= np.zeros((2,1))
Q_k = np.eye(2)*0.1
H_k= lambda pk: np.array([S/((D-pk[0].item())**2+S**2),0])
h_pk_vk = lambda pk,vk: np.arctan(S/(D-pk[0]).item()) + vk

In [4]:
#Prediction
xc_k:np.ndarray = Fk.dot(xh_k) + Gk * u_k
Pc_k = Fk.dot(Ph_k).dot(Fk.T) + Lk.dot(Q_k).dot(Lk.T)

#Optimal gain
K_k = Pc_k.dot((H_k(xc_k)).T)/(H_k(xc_k).dot(Pc_k).dot(H_k(xc_k).T)+Mk*R_k*Mk)

#Correction
xh_k = xc_k + K_k.dot(np.array([yk-h_pk_vk(xc_k,0),0]))
Ph_k = (np.eye(2)-K_k.dot(H_k(xc_k))).dot(Pc_k)

print("Linearized model")
print("H_k",np.round(H_k(xc_k),3))

print("Prediction")
print("xc_k\n",xc_k)
print("Pc_k\n",Pc_k)

print("Optimal gain")
print("K_k\n",np.round(K_k,2))

print("Correction")
print("xh_k\n",np.round(xh_k,2))
print("Ph_k\n",np.round(Ph_k,2))

Linearized model
H_k [0.011 0.   ]
Prediction
xc_k
 [[2.5]
 [4. ]]
Pc_k
 [[0.36 0.5 ]
 [0.5  1.1 ]]
Optimal gain
K_k
 [0.4  0.55]
Correction
xh_k
 [[2.51]
 [4.01]]
Ph_k
 [[0.36 0.49]
 [0.5  1.09]]
